### ISSUE TITLE
Instructions for use

### ISSUE THREAD

**Issue by witnessmenow** [EdJoPaTo/website-changed-bot#2]
Hello,

I was just looking for something that could notify me when a webpage changed and I came across your repo and the name looks promising at least! 

But there is no documentation at all, is it functional at the moment? Is there a docker image we can use?

Thanks

**Comment by EdJoPaTo** [comment]
Hey! Thanks for the interest!

There is a docker image automatically built from this repo: https://hub.docker.com/r/edjopato/websitechangedbot

The bot is currently running as https://t.me/WebsiteChangedBot. It works good enough for my needs but there is definitely room for improvement (I have ideas, time is another story…)

As the bot allows for any url and the server will download that, users are able to load huge things for example. That's why I added access protection to the bot so no "random" user will fill disk space / use it for other harmful stuff. Give me a hint on Telegram (https://t.me/EdJoPaTo) and I allow access.

For hosting it yourself, I have a docker swarm running with this stack config:

```yaml
version: '3.8'

secrets:
  bot-token.txt:
    file: secrets/website-changed-bot-bot-token.txt

volumes:
  git-daemon-workdir:

services:
  telegram-bot:
    image: edjopato/websitechangedbot
    deploy:
      placement:
        constraints:
          - node.hostname==<server where the bind data is>
    secrets:
      - bot-token.txt
    environment:
      PUBLIC_HOSTNAME: <server where the git daemon is, so the bot can show a useable clone link>
    volumes:
      - type: bind
        source: /srv/website-changed-bot/persistent
        target: /app/persistent
      - type: bind
        source: /srv/website-changed-bot/users
        target: /app/users
      - type: bind
        source: /srv/website-changed-bot/websites
        target: /app/websites

  git-daemon:
    image: rohitpaulk/git-daemon-alpine
    command:
      - "daemon"
      - "--export-all"
      - "--base-path=/srv/git/links"
      - "--verbose"
    healthcheck:
      test: git clone git://localhost/test && rm -rf test
      interval: 20m
    ports:
      - target: 9418
        published: 9418
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname==<server where the bind data is>
    volumes:
      - git-daemon-workdir:/git
      - type: bind
        source: /srv/website-changed-bot/websites
        target: /srv/git
        read_only: true
```

The secret contains just the bot token.
